#include "rxn_super_resolution.h"
#include "../main/rxn_config.h" // For RXNSettings struct

// --- PRE-COMPILED COMPUTE SHADER --- //
// This byte array would typically be generated by compiling an HLSL file
// (e.g., using `fxc.exe`) and then exporting the result as a C++ header.
// For example: `fxc /T cs_5_0 /E mainCS /Fo CAS.cso CAS.hlsl`
// followed by a tool to convert CAS.cso to a C++ byte array.
// This is a placeholder for a robust CAS (Contrast Adaptive Sharpening) algorithm.
const unsigned char g_casComputeShader[] = {
    // This is a dummy, minimal compiled compute shader.
    // A real one would be several kilobytes.
    0x44, 0x58, 0x42, 0x43, 0xCF, 0xA6, 0x0C, 0x76, 0xAD, 0x39, 0x27, 0x42, 
    // ... (rest of the shader byte code) ...
}; 

RXNSuperResolution::RXNSuperResolution() = default;

RXNSuperResolution::~RXNSuperResolution() {
    Shutdown();
}

bool RXNSuperResolution::Initialize(ID3D11Device* device) {
    if (!device) return false;

    // Create the compute shader from the pre-compiled byte array.
    HRESULT hr = device->CreateComputeShader(g_casComputeShader, sizeof(g_casComputeShader), nullptr, &m_computeShader);
    if (FAILED(hr)) {
        return false;
    }

    // Create the constant buffer.
    D3D11_BUFFER_DESC cbDesc = {};
    cbDesc.ByteWidth = sizeof(CS_Constants);
    cbDesc.Usage = D3D11_USAGE_DYNAMIC;
    cbDesc.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
    cbDesc.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;

    hr = device->CreateBuffer(&cbDesc, nullptr, &m_constantBuffer);
    return SUCCEEDED(hr);
}

void RXNSuperResolution::Shutdown() {
    SafeRelease(m_upscaledTextureUAV);
    SafeRelease(m_upscaledTexture);
    SafeRelease(m_constantBuffer);
    SafeRelease(m_computeShader);
}

bool RXNSuperResolution::CheckAndCreateResources(ID3D11Device* device, ID3D11Texture2D* input_frame, RXSR_ScalingProfile profile) {
    D3D11_TEXTURE2D_DESC inputDesc;
    input_frame->GetDesc(&inputDesc);

    UINT outputWidth = static_cast<UINT>(inputDesc.Width * (static_cast<int>(profile) / 100.0f));
    UINT outputHeight = static_cast<UINT>(inputDesc.Height * (static_cast<int>(profile) / 100.0f));

    // If the input dimensions or the profile haven't changed, we can reuse the existing resources.
    if (m_upscaledTexture && inputDesc.Width == m_lastInputWidth && inputDesc.Height == m_lastInputHeight && profile == m_lastProfile) {
        return true;
    }

    // Release old resources if they exist.
    SafeRelease(m_upscaledTextureUAV);
    SafeRelease(m_upscaledTexture);

    // Create the output texture with UAV (Unordered Access View) binding.
    D3D11_TEXTURE2D_DESC texDesc = {};
    texDesc.Width = outputWidth;
    texDesc.Height = outputHeight;
    texDesc.MipLevels = 1;
    texDesc.ArraySize = 1;
    texDesc.Format = inputDesc.Format; // Keep the same format.
    texDesc.SampleDesc.Count = 1;
    texDesc.Usage = D3D11_USAGE_DEFAULT;
    texDesc.BindFlags = D3D11_BIND_SHADER_RESOURCE | D3D11_BIND_UNORDERED_ACCESS;
    texDesc.CPUAccessFlags = 0;
    texDesc.MiscFlags = 0;

    HRESULT hr = device->CreateTexture2D(&texDesc, nullptr, &m_upscaledTexture);
    if (FAILED(hr)) return false;

    // Create the UAV for the output texture.
    D3D11_UNORDERED_ACCESS_VIEW_DESC uavDesc = {};
    uavDesc.Format = texDesc.Format;
    uavDesc.ViewDimension = D3D11_UAV_DIMENSION_TEXTURE2D;
    uavDesc.Texture2D.MipSlice = 0;

    hr = device->CreateUnorderedAccessView(m_upscaledTexture, &uavDesc, &m_upscaledTextureUAV);
    if (FAILED(hr)) {
        SafeRelease(m_upscaledTexture);
        return false;
    }

    // Update our cache state.
    m_lastInputWidth = inputDesc.Width;
    m_lastInputHeight = inputDesc.Height;
    m_lastProfile = profile;

    return true;
}

ID3D11Texture2D* RXNSuperResolution::Execute(
    ID3D11DeviceContext* context,
    ID3D11Texture2D* input_frame,
    const RXNSettings& settings,
    RXSR_ScalingProfile profile
) {
    if (!context || !input_frame || !m_computeShader || !m_constantBuffer || profile == RXSR_ScalingProfile::Off) {
        // If SR is off, just return the original frame.
        return input_frame;
    }

    ID3D11Device* device;
    context->GetDevice(&device);

    // Ensure our output resources are correctly sized for the current task.
    if (!CheckAndCreateResources(device, input_frame, profile)) {
        SafeRelease(device);
        return input_frame; // Return original on failure.
    }

    // --- Shader Execution --- //

    // 1. Set the compute shader.
    context->CSSetShader(m_computeShader, nullptr, 0);

    // 2. Update and set the constant buffer.
    D3D11_MAPPED_SUBRESOURCE mappedResource;
    if (SUCCEEDED(context->Map(m_constantBuffer, 0, D3D11_MAP_WRITE_DISCARD, 0, &mappedResource))) {
        CS_Constants* constants = static_cast<CS_Constants*>(mappedResource.pData);
        D3D11_TEXTURE2D_DESC outDesc;
        m_upscaledTexture->GetDesc(&outDesc);
        
        constants->inputWidth = m_lastInputWidth;
        constants->inputHeight = m_lastInputHeight;
        constants->outputWidth = outDesc.Width;
        constants->outputHeight = outDesc.Height;
        constants->sharpeningAmount = settings.sharpeningAmount;
        
        context->Unmap(m_constantBuffer, 0);
    }
    context->CSSetConstantBuffers(0, 1, &m_constantBuffer);

    // 3. Set the input texture as a Shader Resource View (SRV).
    // We assume a simple SRV creation here. A full engine would have a resource manager.
    ID3D11ShaderResourceView* inputSRV = nullptr;
    D3D11_SHADER_RESOURCE_VIEW_DESC srvDesc = {};
    srvDesc.Format = DXGI_FORMAT_UNKNOWN;
    srvDesc.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D;
    srvDesc.Texture2D.MostDetailedMip = 0;
    srvDesc.Texture2D.MipLevels = 1;
    D3D11_TEXTURE2D_DESC inDesc;
    input_frame->GetDesc(&inDesc);
    srvDesc.Format = inDesc.Format;
    device->CreateShaderResourceView(input_frame, &srvDesc, &inputSRV);
    
    context->CSSetShaderResources(0, 1, &inputSRV);

    // 4. Set the output texture as a UAV.
    context->CSSetUnorderedAccessViews(0, 1, &m_upscaledTextureUAV, nullptr);

    // 5. Dispatch the compute shader.
    // We dispatch one thread group for each 8x8 block of pixels in the output texture.
    D3D11_TEXTURE2D_DESC outDesc;
    m_upscaledTexture->GetDesc(&outDesc);
    UINT threadGroupCountX = (outDesc.Width + 7) / 8; // Ceil division
    UINT threadGroupCountY = (outDesc.Height + 7) / 8;
    context->Dispatch(threadGroupCountX, threadGroupCountY, 1);

    // 6. Unbind resources.
    ID3D11ShaderResourceView* nullSRV[1] = { nullptr };
    context->CSSetShaderResources(0, 1, nullSRV);
    ID3D11UnorderedAccessView* nullUAV[1] = { nullptr };
    context->CSSetUnorderedAccessViews(0, 1, nullUAV, nullptr);

    // --- Cleanup --- //
    SafeRelease(inputSRV);
    SafeRelease(device);

    // Return the new, upscaled texture.
    return m_upscaledTexture;
}
